// <auto-generated />
namespace OTProyect.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreatetablePuntosCalorOficial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatetablePuntosCalorOficial));
        
        string IMigrationMetadata.Id
        {
            get { return "202205100440050_Create-table-PuntosCalorOficial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
